// MyPickz — scripts/build.js (ر٧٣-ج البند ٥): يبني الملف المنشور من أجزاء src/ بالترتيب المكتوب في src/build.json — لصق لا تحويل
// الاستعمال: node scripts/build.js            → يكتب index-debug-test.html (ملمح test)
//            node scripts/build.js prod <out>  → يكتب ملمح الإنتاج إلى <out> (لا يُنشر قبل المرحلة د)
// الحارس (tests/audit.js §٢٣) يستدعي build('test') في الذاكرة ويقارنه بالملف المرفوع: أي فرق = تعديل يدوي على المخرج أو جزء لم يُرفع
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..'); const SRC = path.join(ROOT, 'src');
function build(profile){
  const cfg = JSON.parse(fs.readFileSync(path.join(SRC, 'build.json'), 'utf8')); const p = cfg.profiles[profile || 'test']; if (!p) throw new Error('unknown profile ' + profile);
  const names = cfg.parts.map(n => (p.replace && p.replace[n]) || n);
  const texts = names.map(n => { const f = path.join(SRC, n); if (!fs.existsSync(f)) throw new Error('missing part ' + n); const t = fs.readFileSync(f, 'utf8'); if (!t.endsWith('\n')) throw new Error('part must end with a newline: ' + n); return t; });
  const srcHash = crypto.createHash('sha256').update(texts.join('')).digest('hex').slice(0, 8);
  const stamp = '<!-- MyPickz build · profile=' + (profile || 'test') + ' · src=' + srcHash + ' · parts=' + names.length + ' · built from src/ by scripts/build.js — do not edit this file by hand -->\n';
  let out = texts.join(''); const tail = '</html>\n'; if (!out.endsWith(tail)) throw new Error('last part must end with </html>'); out = out.slice(0, -tail.length) + stamp + tail;
  return { out, srcHash, names, output: p.output };
}
module.exports = { build };
if (require.main === module){
  const profile = process.argv[2] || 'test'; const r = build(profile); const dest = process.argv[3] ? path.resolve(process.argv[3]) : path.join(ROOT, r.output);
  if (profile === 'prod' && !process.argv[3]) { console.error('prod profile: pass an explicit output path (it is not published before stage D)'); process.exit(2); }
  fs.writeFileSync(dest, r.out); console.log('built ' + profile + ' → ' + path.relative(ROOT, dest) + ' · parts ' + r.names.length + ' · src ' + r.srcHash + ' · ' + r.out.length + ' chars');
}
